// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_purdelivery;

namespace api_purdelivery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220316020444_InitialCreate3")]
    partial class InitialCreate3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_purdelivery.T_Control_Domestic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionyn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_requis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_line_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_shipm_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promised_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Control_Domestic");
                });

            modelBuilder.Entity("api_purdelivery.T_Control_Evalio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("center_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("center_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment_budget_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expense_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("issuedate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pr_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prepareby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("received")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_and_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resp_suppliercpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("vendor_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendor_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Control_Evalio");
                });

            modelBuilder.Entity("api_purdelivery.T_Control_Oversea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionyn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_line_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_shipm_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promised_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_shipping_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requisitioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Control_Oversea");
                });

            modelBuilder.Entity("api_purdelivery.T_Delay_Domestic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("byer_pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionyn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_line_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_shipm_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promised_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_and_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requisitioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resp_suppliercpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Delay_Domestic");
                });

            modelBuilder.Entity("api_purdelivery.T_Delay_Oversea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_pic_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionyn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_line_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("po_shipm_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promised_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_and_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_shipping_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requisitioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resp_suppliercpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Delay_Oversea");
                });

            modelBuilder.Entity("api_purdelivery.T_Delay_ShortLT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("branch_number_debit_credit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("champ_reserve1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("champ_reserve2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_acceptance_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_received")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_received_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_to_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chargeable_free_charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check_eod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check_shortlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("class_commodity_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_budget_fixedassets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_fixed_assets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumption_taxamount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cost_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_date_acceptance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_date_receiving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_slipno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_code_pur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_code_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_pur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("error_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estimated_amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fiscal_month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inhouse_order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("invoice_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("invoice_no_domestic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemclass_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ledg_act")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location_code_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nvoice_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organi_code_capitalizing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partition_debit_credit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partition_delivery_slip_output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partition_subcontractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payable_unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_amount_excludetax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_amount_includetax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pic_receiving_acceptance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promised_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promo_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_notapplicable_master")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_accep_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_acceptance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("received_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("received_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regis_chemical_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("revision_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rfq_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipped_location_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stnd_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_item_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_site_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tax_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temporary_up")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("theme_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_other_charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trade_point")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trade_terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unspsc_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("waybill_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("waybill_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wdw")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Delay_ShortLT");
                });

            modelBuilder.Entity("api_purdelivery.T_Domestic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cd_chg_hist_all")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_delv_place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_destin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_insp_type_eiaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_ord_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_ord_resn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_procur_person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_sply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_sply_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_sply_fact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_use_block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cf_rpt_parts_ord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ck_eod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ck_shortlt1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ck_shortlt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cm_coment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_shortlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_acptc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_delv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_rec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("early_dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iv_term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_iv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_ontime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_shortlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_adj_dim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_draw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_ord_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_parts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_split_deiv_sfx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_acptd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_ng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_ord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_rec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_iv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_shortlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tm_acptc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tm_delv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tm_po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tm_rec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tss_result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Domestic");
                });

            modelBuilder.Entity("api_purdelivery.T_Oversea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cd_chg_hist_all")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_delv_place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_destin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_estim_person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_insp_type_eiaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_ord_resn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_sply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_sply_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_sply_fact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cd_use_block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cf_rpt_parts_ord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ck_eod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ck_shortlt1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ck_shortlt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cm_coment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail_shortlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_delv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_delv_bal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_delv_dirct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_delv_estim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dt_rec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("early_dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iv_term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_iv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_ontime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mk_shortlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_adj_dim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_arrange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_draw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_invoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_parts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("no_split_deiv_sfx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_delv_dirct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_ng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_ord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qt_rec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_iv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_shortlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tm_delv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tm_po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tm_rec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tss_result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Oversea");
                });

            modelBuilder.Entity("api_purdelivery.T_PO_Issue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accounting_month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("amount_delivered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approved_req_amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approver_info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approver_msg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approver_msg2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("arrival_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("arrival_req_date_plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asset_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attached_file_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attached_file_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("budget_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cancel_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catalog_validity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chemical_subs_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_pic_inspection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_pic_receiving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("control")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_time_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_incharge_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direct_delivery_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("discourse_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eta_actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etd_actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expense_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expense_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("finish_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_budget_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_buyer_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_order_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_po_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_quotation_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_quotation_replyno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspec_creditdebit_approver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspec_pic_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspec_receive_creat_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspec_receive_pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspec_timeday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("install_adjust_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lead_time_reply_quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maximum_unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ng_amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officlal_unitprice_changeplan_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ok_amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_approver1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_approver2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_approver3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_approver4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_cheapest_supp_quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_lead_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_reason_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_remain_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_sheet_output_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordered_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordered_person_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordered_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pr_approve_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_update_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quotation_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quotation_reply_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quotation_req_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receipt_regis_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receipt_regis_person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receipt_regis_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_creat_pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_pic_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiving_creat_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_compny_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_receive_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requested_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rfq1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rfq2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rfq3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rfq_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("risk_level_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("send_delivery_actual_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source_breakdown_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source_document_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standard_unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standard_unit_price_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subcontract_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_reply_quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_selection_reason_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temporary_unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temporary_unit_price_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trade_condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_price_reason_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_price_reply_quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unspsc_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usage_at")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_PO_Issue");
                });

            modelBuilder.Entity("api_purdelivery.T_PU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("date_passed_after_reception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_date_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ship_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_PU");
                });

            modelBuilder.Entity("api_purdelivery.T_PU_Abnormal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_passed_after_reception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_date_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ship_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_PU_Abnormal");
                });

            modelBuilder.Entity("api_purdelivery.T_PU_Original", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("date_passed_after_reception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_date_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ship_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("upd_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("upd_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_PU_Original");
                });
#pragma warning restore 612, 618
        }
    }
}
