// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_purdelivery;

namespace api_purdelivery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220315071120_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_purdelivery.T_Control_Domestic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Requis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Line_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Shipm_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Promised_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionYN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Control_Domestic");
                });

            modelBuilder.Entity("api_purdelivery.T_Control_Evalio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Center_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Center_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment_Budget_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expense_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PR_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prepareby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark_and_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resp_supplierCPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Control_Evalio");
                });

            modelBuilder.Entity("api_purdelivery.T_Control_Oversea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Line_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Shipm_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Promised_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionYN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_shipping_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Control_Oversea");
                });

            modelBuilder.Entity("api_purdelivery.T_Delay_Domestic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Byer_PIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Line_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Shipm_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Promised_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark_and_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resp_SupplierCPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionYN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Delay_Domestic");
                });

            modelBuilder.Entity("api_purdelivery.T_Delay_Oversea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Line_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Shipm_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Promised_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark_and_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resp_SupplierCPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Today")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("balanced_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_belong_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_mailddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_PIC_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_balanced_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspectionYN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark_risk_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_shipping_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("request_dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requester_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Delay_Oversea");
                });

            modelBuilder.Entity("api_purdelivery.T_Delay_ShortLT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CHAMP_reserve1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHAMP_reserve2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cost_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inhouse_Order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIC_receiving_acceptance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProMo_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQ_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supp_Site_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNSPSC_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("branch_number_debit_credit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_acceptance_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_received")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_received_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charge_to_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chargeable_free_charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check_EOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check_ShortLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("class_commodity_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_Budget_FixedAssets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_Fixed_Assets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumption_taxamount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_date_acceptance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creation_date_receiving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_SlipNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_code_pur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_code_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_pur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("error_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estimated_amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fiscal_month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("invoice_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("invoice_No_Domestic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemclass_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ledg_act")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location_code_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nvoice_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organi_Code_Capitalizing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partition_debit_credit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partition_delivery_slip_output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partition_subcontractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payable_unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_amount_excludeTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_amount_includeTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promised_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_order_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason_notapplicable_master")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_accep_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_acceptance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("received_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regis_chemical_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("revision_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipped_location_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stnd_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_Item_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supp_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tax_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temporary_up")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("theme_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_other_charge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trade_point")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trade_terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("waybill_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("waybill_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wdw")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_Delay_ShortLT");
                });

            modelBuilder.Entity("api_purdelivery.T_Domestic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CD_CHG_HIST_ALL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DELV_PLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DESTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_INSP_TYPE_EIAJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_ORD_CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_ORD_RESN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_PROCESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_PROCUR_PERSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SPLY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SPLY_CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SPLY_FACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_USE_BLOCK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CF_RPT_PARTS_ORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CK_EOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CK_ShortLT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CK_ShortLT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CM_COMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_ACPTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_DELV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_PO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_DV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_Early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_ShortLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EARLY_DV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IV_TERM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_DV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_Early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_IV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_ONTIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_ShortLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_ADJ_DIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_DRAW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_ORD_CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_PARTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_PO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_SPLIT_DEIV_SFX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_ACPTD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_NG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_ORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_Early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_IV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_ShortLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM_ACPTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM_DELV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM_PO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TSS_Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Domestic");
                });

            modelBuilder.Entity("api_purdelivery.T_Oversea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CD_CHG_HIST_ALL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DELV_PLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DESTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_ESTIM_PERSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_INSP_TYPE_EIAJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_ORD_RESN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_PROCESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SPLY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SPLY_CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SPLY_FACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_USE_BLOCK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CF_RPT_PARTS_ORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CK_EOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CK_ShortLT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CK_ShortLT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CM_COMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_DELV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_DELV_BAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_DELV_DIRCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_DELV_ESTIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_PO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_DV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_Early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_ShortLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EARLY_DV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IV_TERM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_DV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_Early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_IV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_ONTIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MK_ShortLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_ADJ_DIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_ARRANGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_DRAW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_INVOICE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_PARTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_PO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NO_SPLIT_DEIV_SFX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_DELV_DIRCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_NG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_ORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_Delay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_Early")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_IV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason_ShortLT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM_DELV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM_PO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM_REC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TSS_Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("T_Oversea");
                });

            modelBuilder.Entity("api_purdelivery.T_PO_Issue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accounting_Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approver_MSG1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approver_MSG2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arrival_Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arrival_Req_Date_Plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attached_File_Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attached_File_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Buyer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cancel_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catalog_Validity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chemical_Subs_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_PIC_Inspection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_PIC_Receiving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Creation_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Creation_Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Time_Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dept_InCharge_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direct_Delivery_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discourse_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETA_Actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETD_Actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Budget_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Buyer_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Maker_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Order_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_PO_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Quotation_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Quotation_ReplyNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspec_CreditDebit_Approver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspec_PIC_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspec_Receive_Creat_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspec_Receive_PIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspec_TimeDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Install_Adjust_Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lead_Time_Reply_Quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maximum_Unit_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NG_Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OK_Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Officlal_UnitPrice_ChangePlan_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Approver1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Approver2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Approver3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Approver4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Cheapest_Supp_Quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Lead_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Reason_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Remain_Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Sheet_Output_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ordered_Company_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ordered_Person_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PR_Approve_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program_Update_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quotation_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quotation_Reply_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quotation_Req_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQ1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQ2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQ3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFQ_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receipt_Regis_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receipt_Regis_Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receipt_Regis_Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receive_Creat_PIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receive_PIC_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiving_Creat_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Req_Company_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Req_Compny_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Req_Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risk_Level_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Send_Delivery_Actual_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_Breakdown_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_Document_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard_Unit_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard_Unit_Price_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcontract_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supp_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supp_Reply_Quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supp_Selection_Reason_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temporary_Unit_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temporary_Unit_Price_Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trade_Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNSPSC_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit_Price_Reason_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Price_Reply_Quotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Update_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Update_Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("account_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("amount_delivered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approved_Req_amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approver_info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asset_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("budget_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("control")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expense_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expense_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("finish_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inspection_category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordered_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_receive_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requested_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usage_at")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_PO_Issue");
                });

            modelBuilder.Entity("api_purdelivery.T_PU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("date_passed_after_reception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_date_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ship_To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_PU");
                });

            modelBuilder.Entity("api_purdelivery.T_PU_Abnormal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("date_passed_after_reception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_date_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ship_To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_PU_Abnormal");
                });

            modelBuilder.Entity("api_purdelivery.T_PU_Original", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPD_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPD_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("date_passed_after_reception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maker_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_wdw_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_incharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pur_req_qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receive_date_pur_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_delivery_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_details_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("req_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ship_To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("T_PU_Original");
                });
#pragma warning restore 612, 618
        }
    }
}
