using System;
using System.ComponentModel.DataAnnotations;

namespace api_purdelivery
{
    public class T_Delay_ShortLT
    {
        public int ID { get; set; }
        public string subject { get; set; }
         public string req_no { get; set; }
        public string pur_order_no { get; set; }
        public string receive_number { get; set; }
        public string branch_number_debit_credit { get; set; }
        public string partition_debit_credit { get; set; }
        public string rfq_number { get; set; }
        public string supp_code { get; set; }
        public string supp_name { get; set; }
        public string supp_site_code { get; set; }
        public string partition_delivery_slip_output { get; set; }
        public string supp_item_code { get; set; }
        public string partition_subcontractor { get; set; }
        public string maker_code { get; set; }
        public string maker_name { get; set; }
        public string type { get; set; }
        public string itemclass_code { get; set; }
        public string unspsc_code { get; set; }
        public string class_commodity_code { get; set; }
        public string item_desc { get; set; }
        public string wdw { get; set; }
        public string charge_to { get; set; }
        public string charge_to_name { get; set; }
        public string ledg_act { get; set; }
        public string cost_item { get; set; }
        public string ctrl { get; set; }
        public string inhouse_order { get; set; }
        public string code_budget_fixedassets { get; set; }
        public string code_fixed_assets { get; set; }
        public string organi_code_capitalizing { get; set; } 
        public string country_origin  { get; set; }
        public string promo_no { get; set; }
        public string regis_chemical_item { get; set; }
        public string theme_id { get; set; }
        public string revision_no { get; set; }
        public string temporary_up { get; set; }
        public string inspection_yn { get; set; }
        public string unit { get; set; }
        public string currency { get; set; }
        public string reason_notapplicable_master { get; set; }
        public string shipped_location_code { get; set; }
        public string payment_terms { get; set; }
        public string order_date { get; set; }
        public string promised_date { get; set; }
        public string received_date { get; set; }
        public string receive_acceptance { get; set; }
        public string check_shortlt { get; set; }
        public string check_eod { get; set; }
        public string status { get; set; }
        public string cause { get; set; }
        public string department { get; set; }
        public string reason { get; set; }
        public string creation_date_receiving { get; set; }
        public string creation_date_acceptance { get; set; }
        public string fiscal_month { get; set; }
        public string stnd_price { get; set; }
        public string order_unit_price { get; set; }
        public string payable_unit_price { get; set; }
        public string pur_req_qty { get; set; }
        public string pur_order_qty { get; set; }
        public string received_qty { get; set; }
        public string receive_accep_qty { get; set; }
        public string estimated_amount { get; set; }
        public string payment_amount_excludetax { get; set; }
        public string consumption_taxamount { get; set; }
        public string payment_amount_includetax { get; set; }
        public string tax_code { get; set; }
        public string rate { get; set; }
        public string waybill_no { get; set; }
        public string nvoice_no { get; set; }
        public string chargeable_free_charge { get; set; }
        public string trade_terms { get; set; }
        public string trade_point { get; set; }
        public string transportation { get; set; }
        public string waybill_date { get; set; }
        public string invoice_date { get; set; }
        public string delivery_slipno { get; set; }
        public string invoice_no_domestic { get; set; }
        public string total_other_charge { get; set; }
        public string responsibility { get; set; }
        public string pur_req_company_code { get; set; }
        public string location_code_pur_req { get; set; }
        public string dept_code_pur_req { get; set; }
        public string dept_pur_req { get; set; }
        public string pur_company_code { get; set; }
        public string dept_code_pur { get; set; }
        public string dept_pur { get; set; }
        public string pur_incharge_code { get; set; }
        public string pur_incharge { get; set; }
        public string charge_received_company_code { get; set; }
        public string charge_received { get; set; }
        public string charge_acceptance_company_code { get; set; }
        public string pic_receiving_acceptance { get; set; }
        public string error_flag { get; set; }
        public string transaction_id { get; set; }
        public string last_update_date { get; set; }
        public string last_update_by { get; set; }
        public string creation_date { get; set; }
        public string created_by { get; set; }
        public string champ_reserve1 { get; set; }
        public string champ_reserve2 { get; set; }
        public DateTime? upd_dt { get; set; } 
        public string upd_by { get; set; } 
        public string input_by { get; set; }
        public DateTime? input_dt { get; set; } 
    }
}