import { Component, enableProdMode, OnInit, ViewChild } from '@angular/core';
import { DxDataGridComponent } from 'devextreme-angular';
import notify from 'devextreme/ui/notify';
import { Service } from 'src/app/shared/services';
import { environment } from 'src/environments/environment';

if (environment.production) {
  enableProdMode();
}
@Component({
  selector: 'app-input-dl3-oversea',
  templateUrl: './input-dl3-oversea.component.html',
  styleUrls: ['./input-dl3-oversea.component.scss'],
  providers: [Service]
})
export class InputDl3OverseaComponent implements OnInit {
  @ViewChild(DxDataGridComponent, { static: false })
  dataGrid!: DxDataGridComponent;
  Oversea:  any[] = [];
  selectedItemKeys: any[] = [];
  dateupOptions: any[] = [];
  selectBoxOptions: any;
  refreshButtonOptions: any;

  constructor(service: Service, public apiPUR: Service) {
    // this.Domestic = domecticGrid;
    this.getsubject();

    this.refreshButtonOptions = {
      icon: 'refresh',
      onClick: () => {
        notify('Refresh button has been clicked!');
      },
    };
    
   }
  ngOnInit(): void {
  }
  async getsubject(){ 
    let data = await this.apiPUR.sv_getreason("Input_reasonpur3/get_subject_cnt_oversea");
    console.log(data)
     this.dateupOptions = data;
     this.getdata(this.dateupOptions[0]);
     this.selectBoxOptions = {
       width: 240,
       items: this.dateupOptions,
       value: this.dateupOptions[0],
       onValueChanged: (e: any) => {
      this.getdata(e.value);
       },
     };
   }
   async getdata(sbj: string){ 
     let data = await this.apiPUR.sv_post_paramEUC("Input_reasonpur3/get_oversea_row","?sbj=" + sbj);
     this.Oversea = data;
   }
  selectionChanged(data: any) {
    this.selectedItemKeys = data.selectedRowKeys;
  }
  onExporting(e: any) {
    console.log('onExporting',e)
    
  }

}
export class ControlDomestic {
  ID!: number;
  Status!: string;
  PO_Number!: string;
  PO_Line!: string;
  PO_Shipment!: string;
  req_no!: string;
  req_details!: string;
  pur_incharge!: string;
  Supplier!: string;
  supplier_site!: string;
  Item_Des!: string;
  maker!: string;
  type!: string;
  Price!: string;
  Currency!: string;
  order_qty!: string;
  delive_qty!: string;
  balanced_qty!: string;
  balanced_order_qty!: string;
  unit!: string;
  inspection!: string;
  Order_Date!: string;
  req_shipping_date!: string;
  Promised_Date!: string;
  Today_date!: string;
  Delay!: string;
  LT!: string;
  Check!: string;
  transport!: string;
  Requisitioner!: string;
  request_dept!: string;
  request_Email!: string;
  date_up!: string;
}

const domecticGrid: ControlDomestic[] = [{
  ID: 1 ,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 4,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 5,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 11,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 14,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 15,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 30,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 32,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 36,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 39,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 42,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 46,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 47,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 51,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 56,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 57,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 59,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 65,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 66,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 69,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 78,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 81,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 83,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 84,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 85,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 87,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 88,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}, {
  ID: 91,
  Status: 'Approved' ,
  PO_Number: '251100061070' ,
  PO_Line: '1' ,
  PO_Shipment: '1' ,
  req_no: '151010092935' ,
  req_details: '1' ,
  pur_incharge: 'BURANAPAN MATHAWEE' ,
  Supplier: '988A_CANON MARKETING (THAILAND) CO.,LTD.' ,
  supplier_site: '0' ,
  Item_Des: 'Repair Scanner' ,
  maker: 'Canon' ,
  type: 'DR-M260 (S/N.HG406570)' ,
  Price:'4554000',
  Currency:'JPY',
  order_qty: '1' ,
  delive_qty: '0',
  balanced_qty: '1' ,
  balanced_order_qty: '1' ,
  unit: 'PCS' ,
  inspection: 'No' ,
  Order_Date: '1/11/2022' ,
  req_shipping_date: '1/5/2022',
  Promised_Date: '1/24/2022' ,
  Today_date: '1/17/2022' ,
  Delay: '7' ,
  LT: '-13' ,
  Check: '' ,
  transport: 'AIR',
  Requisitioner: 'RAKSAPHOL WANNAPHA' ,
  request_dept: 'ASSEMBLY ADMINISTRATION DEPT.' ,
  request_Email: 'wannapha@mail.canon',
  date_up:'02-11-2021'
}];